function Service() {
	return(
			<>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			<h1>Service</h1>
			</>
		);
}
export default Service;